apiVersion: v1
kind: Service
metadata:
  name: edgecontroller
  namespace: kubeedge
  labels:
    k8s-app: kubeedge
    kubeedge: edgecontroller
spec:
  type: NodePort
  ports:
  - name: cloudhub
    port: 10000
    nodePort: 31337
  - name: debug
    port: 2345
    nodePort: 32345
  selector:
    k8s-app: kubeedge
    kubeedge: edgecontroller
