all:
  vars:
    ansible_ssh_extra_args: -o StrictHostKeyChecking=no
    ansible_ssh_user: vagrant
    k3s_token: 1018af34ad6707e53041f8b2ccd3f3dc
  children:
    master:
      hosts:
        192.168.69.2:
          ansible_ssh_private_key_file: .vagrant/machines/master/virtualbox/private_key
          vars:
            wg_ip: 10.112.0.1
            wg_private_key: cI51/+JENUzUztNHoDZyYvCiZ833BM2Z3C7WRvAPbFg=
            wg_public_key: sJsaywr1e4lup7+WLA0ZK5NJmYzzqSnCtrQqSvv0QHM=
            k8s_hostname: kubeedge-master
    worker:
      children:
        cloud:
          hosts:
            192.168.69.3:
              ansible_ssh_private_key_file: .vagrant/machines/worker/virtualbox/private_key
              vars:
                wg_ip: 10.112.0.50
                wg_private_key: mIEQJ/8oSoxtt0uaJYsdr+g7XlIw5xIF/cFL3qtlxns=
                wg_public_key: zrtvEkLj/cxhKZ32Yg2YqCg2IYdsukIu7c5/P71X01I=
                k8s_hostname: kubeedge-worker
        edge:
          hosts:
            127.0.0.1:
              ansible_ssh_user: edge
              ansible_ssh_pass: edge
              ansible_ssh_port: 2022
              vars:
                wg_ip: 10.112.0.51
                wg_private_key: oBABPseRkCIN3lGAW+xq/qnHmp9cEfx+Th1Y7SMmU14=
                wg_public_key: Z2uGbn1AaprbyUa1SjbPw9GYEuWDZifQmtk13AF60XI=
                k8s_hostname: kubeedge-edge
