all:
  vars:
    ansible_ssh_user: vagrant
  children:
    master:
      hosts:
        192.168.69.2:
          ansible_ssh_private_key_file: .vagrant/machines/master/virtualbox/private_key
          vars:
            wg_ip: 10.112.0.1
            wg_private_key: cI51/+JENUzUztNHoDZyYvCiZ833BM2Z3C7WRvAPbFg=
            wg_public_key: sJsaywr1e4lup7+WLA0ZK5NJmYzzqSnCtrQqSvv0QHM=
    worker:
      hosts:
        192.168.69.3:
          ansible_ssh_private_key_file: .vagrant/machines/worker/virtualbox/private_key
          vars:
            wg_ip: 10.112.0.50
            wg_private_key: mIEQJ/8oSoxtt0uaJYsdr+g7XlIw5xIF/cFL3qtlxns=
            wg_public_key: zrtvEkLj/cxhKZ32Yg2YqCg2IYdsukIu7c5/P71X01I=
        192.168.69.4:
          ansible_ssh_private_key_file: .vagrant/machines/edge/virtualbox/private_key
          vars:
            wg_ip: 10.112.0.51
            wg_private_key: oBABPseRkCIN3lGAW+xq/qnHmp9cEfx+Th1Y7SMmU14=
            wg_public_key: Z2uGbn1AaprbyUa1SjbPw9GYEuWDZifQmtk13AF60XI=

