- name: Log CPU, memory, and storage usage to usage.csv
  shell: |
    rm /tmp/usage.csv

    start_time=$(date +%s)
    duration=60

    echo "time,cpu,mem,storage" >> /tmp/usage.csv

    while true; do
        current_time=$(date +%s)
        elapsed_time=$((current_time - start_time))
        if [ $elapsed_time -ge $duration ]; then
            break
        fi

        echo -n "$current_time," >> /tmp/usage.csv

        top -bn1 | awk 'NR>7 { cpu+=$9 } END { printf("%.2f,", cpu) }' >> /tmp/usage.csv && free --mega | awk 'NR==2 { printf $3"," }' >> /tmp/usage.csv && df -m / | awk 'NR==2 { printf $3"\n" }' >> /tmp/usage.csv
        sleep 1
    done
  register: usage

- name: Copy usage.csv to local machine
  fetch:
    src: /tmp/usage.csv
    dest: .../../../../results/usage-{{ orchestrator }}-{{ inventory_hostname }}.csv
    flat: yes