apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-sensor-simulator
spec:
  selector:
    matchLabels:
      app: iot-sensor-simulator
  replicas: 1
  template:
    metadata:
      labels:
        app: iot-sensor-simulator
    spec:
      nodeSelector:
        node-role.kubernetes.io/edge: "true"
      containers:
        - name: iot-sensor-simulator
          image: bintangbahy/iot-sensor-simulator:latest
          env:
            - name: MOSCA_BROKER
              value: mosquitto

---
apiVersion: v1
kind: Service
metadata:
  name: iot-sensor-simulator
spec:
  selector:
    app: iot-sensor-simulator
  ports:
    - name: http
      port: 9393
      targetPort: 9393
