apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodered
spec:
  selector:
    matchLabels:
      app: nodered
  replicas: 1
  template:
    metadata:
      labels:
        app: nodered
    spec:
      nodeSelector:
        cloud-computing/worker: "true"
      containers:
        - name: nodered
          image: nodered/node-red:2.1.3
          ports:
            - containerPort: 1880
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: nodered
spec:
  selector:
    app: nodered
  ports:
    - name: http
      port: 1880
      targetPort: 1880
