- name: restart-wireguard
  ansible.builtin.service:
    name: wg-quick@wg0
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: enable-wireguard
  systemd:
    name: wg-quick@wg0
    enabled: yes
    state: started
