- name: Install needed package
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  loop:
    - wget
    - gpg
    - coreutils
    - containerd

- name: Add HashiCorp GPG key
  shell: |
    [ -f /usr/share/keyrings/hashicorp-archive-keyring.gpg ] && exit 0
    wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list

- name: Install Nomad
  apt:
    update_cache: yes
    name: nomad
    state: present


- name: Install CNI plugins
  shell: |
    curl -L -o cni-plugins.tgz "https://github.com/containernetworking/plugins/releases/download/v1.0.0/cni-plugins-linux-$( [ $(uname -m) = aarch64 ] && echo arm64 || echo amd64)"-v1.0.0.tgz
    mkdir -p /opt/cni/bin
    tar -C /opt/cni/bin -xzf cni-plugins.tgz
    rm cni-plugins.tgz

- name: Enable sysconfig entries
  shell: |
    echo 1 | tee /proc/sys/net/bridge/bridge-nf-call-arptables
    echo 1 | tee /proc/sys/net/bridge/bridge-nf-call-ip6tables
    echo 1 | tee /proc/sys/net/bridge/bridge-nf-call-iptables
  ignore_errors: true
  
- name: Make plugins directory
  file:
    path: /opt/nomad/data/plugins
    state: directory
    mode: 0755

- name: Install Nomad containerd driver
  shell: |
    wget https://github.com/Roblox/nomad-driver-containerd/releases/download/v0.9.3/containerd-driver -O /opt/nomad/data/plugins/containerd-driver
    chmod +x /opt/nomad/data/plugins/containerd-driver
  when: inventory_hostname not in groups['edge']
  notify: Restart Nomad

- name: Install Nomad containerd driver for edge
  shell: |
    wget https://cloudcomputingfiles.blob.core.windows.net/containerd-driver/containerd-driver -O /opt/nomad/data/plugins/containerd-driver
    chmod +x /opt/nomad/data/plugins/containerd-driver
  when: inventory_hostname in groups['edge']
  notify: Restart Nomad

- name: Configure Nomad
  template:
    src: nomad.hcl.j2
    dest: /etc/nomad.d/nomad.hcl
    owner: root
    group: root
    mode: 0644

- name: Enable Nomad
  systemd:
    name: nomad
    enabled: yes
    state: started